version: '3.9'

networks:
  apinet:
    driver: bridge

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: PracticeAPI/Dockerfile
    container_name: api_container
    depends_on:
      - sql_db
    restart: always
    ports:
      - "24185:80"
    networks:
      - apinet
    environment:
    - ASPNETCORE_ENVIRONMENT=Development

  sql_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_db_container
    restart: always
    environment:
      SA_PASSWORD: RqpTCfaKm1CNffS
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - apinet